[project]
name = "shisho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dateparser>=1.4.0",
    "discord-py>=2.7.1",
    "google-genai>=2.8.0",
    "imapclient>=3.1.0",
    "pocketbase>=0.17.3",
    "PyGithub>=2.6.1",
    "python-dotenv>=1.0.1",
    "sentry-sdk>=2.60.0",
]
