"""
utils/pdf.py - PDF generation and validation utilities for Shisho.
"""

import html
import io
import re
from typing import Optional

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import legal, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import HRFlowable, KeepTogether, Paragraph, Preformatted, SimpleDocTemplate, Spacer


def is_pdf(data: bytes) -> bool:
    """Check if the provided binary data has a valid PDF magic header."""
    if not data or len(data) < 5:
        return False
    return data.startswith(b"%PDF-")


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and render total page count."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            page_width = self._pagesize[0] if hasattr(self, "_pagesize") and self._pagesize else letter[0]
            self.draw_page_decorations(num_pages, page_width=page_width)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int, page_width: Optional[float] = None):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(HexColor("#666666"))

        if page_width is None:
            page_width = self._pagesize[0] if hasattr(self, "_pagesize") and self._pagesize else letter[0]

        # Footer: left side branding, right side page numbers
        footer_y = 0.45 * inch
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_width - 0.75 * inch, footer_y, page_text)
        self.drawString(0.75 * inch, footer_y, "Generated by Shisho")

        # Subtle divider line above footer
        self.setStrokeColor(HexColor("#E0E0E0"))
        self.setLineWidth(0.5)
        self.line(0.75 * inch, footer_y + 12, page_width - 0.75 * inch, footer_y + 12)

        self.restoreState()


def _format_inline_markdown(text: str) -> str:
    """Converts basic markdown inline styles (bold, italic, code) to ReportLab XML tags."""
    # Escape raw HTML special characters first
    escaped = html.escape(text)

    # Inline code: `code` -> <font name="Courier">code</font>
    escaped = re.sub(
        r"`([^`]+)`",
        r'<font name="Courier" color="#333333">\1</font>',
        escaped,
    )
    # Bold: **text** or __text__ -> <b>text</b>
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", escaped)
    escaped = re.sub(r"__([^_]+)__", r"<b>\1</b>", escaped)

    # Italic: *text* or _text_ -> <i>text</i>
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", escaped)
    escaped = re.sub(r"(?<!_)_([^_]+)_(?!_)", r"<i>\1</i>", escaped)

    return escaped


def compile_text_to_pdf(
    text: str,
    title: Optional[str] = None,
    paper_size: str = "letter",
) -> bytes:
    """
    Compiles plaintext or Markdown into a clean, valid PDF document (letter or legal size, 0.75" margins).
    Produces strict %PDF-1.4 output suitable for CUPS printing without filter crashes.
    """
    if not text:
        text = "(Empty Document)"

    norm_size = (paper_size or "letter").strip().lower()
    selected_pagesize = legal if norm_size == "legal" else letter

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=selected_pagesize,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title=title or "Document",
    )

    base_styles = getSampleStyleSheet()

    body_style = ParagraphStyle(
        "ShishoBody",
        parent=base_styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=HexColor("#222222"),
        spaceAfter=4,
    )

    bullet_style = ParagraphStyle(
        "ShishoBullet",
        parent=body_style,
        leftIndent=16,
        firstLineIndent=-12,
        spaceAfter=3,
    )

    h1_style = ParagraphStyle(
        "ShishoH1",
        parent=base_styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=HexColor("#111111"),
        spaceBefore=12,
        spaceAfter=8,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "ShishoH2",
        parent=base_styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=HexColor("#222222"),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True,
    )

    h3_style = ParagraphStyle(
        "ShishoH3",
        parent=base_styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=HexColor("#333333"),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True,
    )

    code_style = ParagraphStyle(
        "ShishoCode",
        fontName="Courier",
        fontSize=8.5,
        leading=11.5,
        textColor=HexColor("#1A1A1A"),
    )

    callout_style = ParagraphStyle(
        "ShishoCallout",
        parent=body_style,
        leftIndent=14,
        textColor=HexColor("#444444"),
        fontName="Helvetica-Oblique",
        spaceAfter=4,
    )

    story = []
    lines = text.splitlines()

    in_yaml_frontmatter = False
    in_code_block = False
    code_block_lines: list[str] = []

    for idx, line in enumerate(lines):
        # 1. Frontmatter YAML stripping
        if idx == 0 and line.strip() == "---":
            in_yaml_frontmatter = True
            continue
        if in_yaml_frontmatter:
            if line.strip() == "---":
                in_yaml_frontmatter = False
            continue

        # 2. Code blocks
        if line.strip().startswith("```"):
            if in_code_block:
                in_code_block = False
                joined_code = "\n".join(code_block_lines)
                if joined_code.strip():
                    story.append(
                        Preformatted(html.escape(joined_code), code_style)
                    )
                    story.append(Spacer(1, 6))
                code_block_lines = []
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_block_lines.append(line)
            continue

        stripped = line.strip()

        # 3. Blank lines
        if not stripped:
            story.append(Spacer(1, 6))
            continue

        # 4. Headings
        if stripped.startswith("# "):
            story.append(Paragraph(_format_inline_markdown(stripped[2:]), h1_style))
        elif stripped.startswith("## "):
            story.append(Paragraph(_format_inline_markdown(stripped[3:]), h2_style))
        elif stripped.startswith("### "):
            story.append(Paragraph(_format_inline_markdown(stripped[4:]), h3_style))

        # 5. Horizontal rules / dividers (e.g. ---, ===, * * *)
        elif stripped in ("---", "===", "***") or re.match(r"^[=\-_*]{4,}$", stripped):
            story.append(
                HRFlowable(
                    width="100%",
                    thickness=0.75,
                    color=HexColor("#CCCCCC"),
                    spaceBefore=6,
                    spaceAfter=6,
                )
            )

        # 6. Blockquotes / Obsidian callouts
        elif stripped.startswith(">"):
            quote_text = stripped.lstrip("> ").strip()
            # Clean callout headers like [!info]
            quote_text = re.sub(r"^\[![A-Za-z_-]+\]\s*", "", quote_text)
            story.append(Paragraph(_format_inline_markdown(quote_text), callout_style))

        # 7. Unordered lists
        elif stripped.startswith(("- ", "* ", "• ")):
            item_text = stripped[2:].strip()
            story.append(
                Paragraph(f"&bull; {_format_inline_markdown(item_text)}", bullet_style)
            )

        # 8. Ordered lists (e.g. "1. ", "12. ")
        elif re.match(r"^\d+\.\s+", stripped):
            prefix_match = re.match(r"^(\d+\.)\s+", stripped)
            num_prefix = prefix_match.group(1) if prefix_match else ""
            item_text = stripped[len(num_prefix) :].strip()
            story.append(
                Paragraph(
                    f"<b>{num_prefix}</b> {_format_inline_markdown(item_text)}",
                    bullet_style,
                )
            )

        # 9. Regular text paragraph
        else:
            story.append(Paragraph(_format_inline_markdown(line), body_style))

    # Catch unclosed code block if file ended inside code
    if in_code_block and code_block_lines:
        story.append(
            Preformatted(html.escape("\n".join(code_block_lines)), code_style)
        )

    # Ensure at least one element exists
    if not story:
        story.append(Paragraph("(Empty Document)", body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()
